# Generated by Django 4.2.7 on 2023-12-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0004_transaction_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_item',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
