# Generated by Django 5.0 on 2023-12-07 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0006_alter_item_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='customer_id',
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
