# Generated by Django 5.0 on 2023-12-07 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0007_remove_transaction_customer_id_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos_app.customer'),
        ),
    ]
